### ISSUE TITLE
Table Styling Example in 7.3+

### ISSUE THREAD

**Issue by marccameron3d** [imulus/TableEditor#9]
Hey, this isnt necessarily an issue with any code , more so the documentation. 
Could you please provide an example of what you would be expected to place into the Table,Row and Column styles sections within the property editor settings?

I cant seem to get the Table to list any styles to use and in effect I believe its not displaying at all in the back office.

![ScreenShot](https://cloud.githubusercontent.com/assets/4186368/10609722/ded85af8-773c-11e5-88af-a044d9da7531.PNG)

All the best,

M

**Comment by kgiszewski** [comment]
It looks like the style is jacked up (v7.3 is my guess).

The format to enter in the prevalues should be of this form `My Style,my-class`

<img width="762" alt="screen shot 2015-10-20 at 10 53 18 am" src="https://cloud.githubusercontent.com/assets/4653907/10611173/dd7b5350-7718-11e5-9834-030d1474df49.png">
<img width="1086" alt="screen shot 2015-10-20 at 10 53 35 am" src="https://cloud.githubusercontent.com/assets/4653907/10611172/dd7892b4-7718-11e5-8c60-d452bb4744b2.png">

Due to other issues, I'm avoiding 7.3 at the moment but hope to have this package updated in the coming weeks.

**Comment by marccameron3d** [comment]
Thanks for getting back to me, yeah looks like 7.3 is causing issues. Ill hold off, cheers.
